### ISSUE TITLE
icone telefone, E-mail

### ISSUE THREAD

**Issue by ecoelhospbrasil** [filipecoelho/moema-web#28]
verificar possibilidade de inserir telefone 11 3217-9900 ao clicar no ícone, e também inserir endereço de e-mail reservas@moematurismo.com.br

**Comment by LEANDROCOELHO84** [comment]
<body>                                                <a id="tel-contact" href="1132179900">
                                                    <i class="fa fa-phone"></i>
                                                    <span class="hidden-xs">(11) 3217-9900</span>
                                                </a>

                                                <a id="tel-contact" href="#">
                                                    <i class="fa fa-phone"></i>
                                                    <span class="hidden-xs">(11) 3217-9900</span>
                                                </a>
                                                                                        
                                              
</body>
